version: "3.8"
services:
  caching:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - RedisVolume:/data
    command: redis-server --requirepass password
  mongodb:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: quiz
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - MongodbVolume:/data/db
volumes:
    RedisVolume:
    MongodbVolume:
networks:
  backend:
    driver: "bridge"
